---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-secret
  namespace: storage
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: garage-secret
    template:
      engineVersion: v2
      data:
        GARAGE_RPC_SECRET: "{{ .GARAGE_RPC_SECRET }}"
        GARAGE_ADMIN_TOKEN: "{{ .GARAGE_ADMIN_TOKEN }}"
        GARAGE_METRICS_TOKEN: "{{ .GARAGE_METRICS_TOKEN }}"
        client-secret: "{{ .GARAGE_WEBUI_OIDC_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: garage-secret
