---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: s3
        group: infrastructure
        url: https://s3-garage.ewatkins.dev
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 403"
