---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: s3
        group: S3
        url: https://s3-garage.ewatkins.dev
        interval: 1m
        ui:
          hide-url: true
        conditions:
          - "[STATUS] == 403"
      - name: garage-health
        group: S3
        url: http://garage-api.storage.svc.cluster.local:3903/health
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
      - name: garage-0
        group: S3
        url: tcp://garage-0.garage.storage.svc.cluster.local:3901
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[CONNECTED] == true"
      - name: garage-1
        group: S3
        url: tcp://garage-1.garage.storage.svc.cluster.local:3901
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[CONNECTED] == true"
      - name: garage-2
        group: S3
        url: tcp://garage-2.garage.storage.svc.cluster.local:3901
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[CONNECTED] == true"
