---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-data
  namespace: storage
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-slow
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-meta
  namespace: storage
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 512Mi
