---
apiVersion: v1
kind: Service
metadata:
  name: garage
  namespace: storage
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: rpc
      port: 3901
      protocol: TCP
