---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-media
spec:
  # RWX: shared by the netbox web pod, the rqworker pod and the housekeeping job
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-scripts
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-fast
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netbox-reports
spec:
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-fast
