---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: minio
        group: internal
        url: https://minio.ewatkins.dev
        interval: 1m
        conditions:
          - "[STATUS] == 200"
      - name: s3
        group: infrastructure
        url: https://s3.ewatkins.dev
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 403"
