---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homelable
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homelable-secret
  dataFrom:
    - extract:
        key: homelable-secret
