---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-server-config
  namespace: development
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-fast
