---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crunchy-postgres-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi #csi-driver-nfs
  nfs:
    server: caspian.local
    path: /mnt/user/crunchy-postgres
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crunchy-postgres-vector-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi #csi-driver-nfs
  nfs:
    server: caspian.local
    path: /mnt/user/crunchy-postgres-vector
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
  persistentVolumeReclaimPolicy: Delete
