---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crunchy-postgres-nfs
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: crunchy-postgres-repo1
    namespace: database
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi
  nfs:
    server: storage.ewatkins.dev
    path: /mnt/user/crunchy-postgres
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
  persistentVolumeReclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crunchy-postgres-vector-nfs
spec:
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: crunchy-postgres-vector-repo1
    namespace: database
  capacity:
    storage: 1Mi
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-csi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: crunchy-postgres-vector-repo1
    namespace: database
  nfs:
    server: storage.ewatkins.dev
    path: /mnt/user/crunchy-postgres-vector
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - nodiratime
    - rsize=131072
    - wsize=131072
    - nconnect=8
  persistentVolumeReclaimPolicy: Delete
