---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/postgres-operator.crunchydata.com/postgrescluster_v1beta1.json
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: &name crunchy-postgres-vector
spec:
  postgresVersion: 16
  image: ghcr.io/budimanjojo/crunchy-postgres-vectorchord:17-0.4.3@sha256:76ed3fd67179d66b8c5a56154d4714680da5557e4507160f10a9aece42465823
  config:
    parameters:
      shared_preload_libraries: vchord.so

  databaseInitSQL:
    name: crunchy-postgres-vector-init-sql
    key: init.sql

  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        pg_hba:
          - hostnossl all all 10.96.0.0/16 md5
          - hostnossl all all 10.69.0.0/16 md5
          - hostnossl all all 10.40.0.0/16 md5
          - hostssl all all all md5

  instances:
    - name: instance
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      walVolumeClaimSpec:
        storageClassName: openebs-hostpath
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: *name
              postgres-operator.crunchydata.com/data: postgres

  users:
    - name: immich
      databases:
        - immich

  backups:
    pgbackrest:
      global:
        repo1-retention-full: "14"
        repo1-retention-full-type: time
        archive-push-queue-max: 4GiB
      repos:
        - name: repo1
          schedules:
            full: "0 2 * * 0"
            incremental: "0 2 * * 1-6"
          volume:
            volumeClaimSpec:
              storageClassName: nfs-csi
              volumeName: crunchy-postgres-vector-nfs
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 1Mi
