apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name sabnzbd-secret
    namespace: media
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          PUSHOVER_TOKEN: "{{ .SABNZBD_PUSHOVER_TOKEN}}"
          PUSHOVER_USER_KEY: "{{ .PUSHOVER_USER_KEY }}"
          SABNZBD__API_KEY: &apiKey "{{ .SABNZBD_API_KEY }}"
          SABNZBD__NZB_KEY: *apiKey
    dataFrom:
      - extract:
          key: *name
      - extract:
          key: pushover
