apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-dns-secret
  namespace: network
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        CF_API_TOKEN: "{{ .api_token }}"
        CF_ZONE_ID: "{{ .zone_id }}"
  dataFrom:
    - extract:
        key: *name
