---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-db-secret
  namespace: media
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres
  target:
    name: *name
    template:
      engineVersion: v2
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        # Paperless DB
        PAPERLESS_DBNAME: '{{ index . "dbname" }}'
        PAPERLESS_DBHOST: '{{ index . "pgbouncer-host" }}'
        PAPERLESS_DBUSER: '{{ index . "user" }}'
        PAPERLESS_DBPASS: '{{ index . "password" }}'
        PAPERLESS_DBPORT: '{{ index . "pgbouncer-port" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-paperless-admin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperless-config-secret
  namespace: media
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        # App
        PAPERLESS_ADMIN_USER: "{{ .PAPERLESS_ADMIN_USER }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .PAPERLESS_ADMIN_PASSWORD }}"
        PAPERLESS_SECRET_KEY: "{{ .PAPERLESS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: *name
