---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name outline-secret
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secret_key }}"
        UTILS_SECRET: "{{ .utils_secret }}"
  dataFrom:
    - extract:
        key: *name
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name outline-oidc
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        OIDC_CLIENT_SECRET: "{{ .client_secret }}"
  dataFrom:
    - extract:
        key: *name
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name outline-bucket
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secret_access_key }}"
  dataFrom:
    - extract:
        key: *name
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name outline-db
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        DATABASE_URL: "postgresql://{{ index . \"user\" }}:{{ index . \"password\" }}@{{ index . \"pgbouncer-host\" }}:{{ index . \"pgbouncer-port\" }}/{{ index . \"dbname\" }}"
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-outline-admin
