metadata_dir = "/meta"
data_dir = "/data"
db_engine = "lmdb"
metadata_auto_snapshot_interval = "6h"

replication_factor = 3
compression_level = 2

rpc_bind_addr = "[::]:3901"
bootstrap_peers = [
    "garage-0.garage.storage.svc.cluster.local:3901",
    "garage-1.garage.storage.svc.cluster.local:3901",
    "garage-2.garage.storage.svc.cluster.local:3901",
]

[s3_api]
s3_region = "us-east-1"
api_bind_addr = "[::]:3900"
root_domain = ".s3-garage.ewatkins.dev"

[admin]
api_bind_addr = "[::]:3903"
