apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-secret
  namespace: security
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        #App
        AUTHENTIK_BOOTSTRAP_EMAIL: "{{ .AUTHENTIK_BOOTSTRAP_EMAIL }}"
        AUTHENTIK_BOOTSTRAP_PASSWORD: "{{ .AUTHENTIK_BOOTSTRAP_PASSWORD }}"
        AUTHENTIK_BOOTSTRAP_TOKEN: "{{ .AUTHENTIK_BOOTSTRAP_TOKEN }}"
        AUTHENTIK_SECRET_KEY: "{{ .AUTHENTIK_SECRET_KEY }}"
        AUTHENTIK_REDIS__DB: "{{ .AUTHENTIK_REDIS__DB }}"
        # Email
        AUTHENTIK_EMAIL__HOST: "{{ .email_host }}"
        AUTHENTIK_EMAIL__PORT: "{{ .email_port }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .email_username }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .email_password }}"
        AUTHENTIK_EMAIL__USE_TLS: "{{ .AUTHENTIK_EMAIL__USE_TLS }}"
        AUTHENTIK_EMAIL__FROM: "{{ .AUTHENTIK_EMAIL__FROM }}"
  dataFrom:
    - extract:
        key: *name
    - extract:
        key: smtp
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name authentik-db-secret
  namespace: security
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        AUTHENTIK_POSTGRESQL__NAME: '{{ index . "dbname" }}'
        AUTHENTIK_POSTGRESQL__HOST: '{{ index . "host" }}'
        AUTHENTIK_POSTGRESQL__PORT: '{{ index . "port" }}'
        AUTHENTIK_POSTGRESQL__USER: '{{ index . "user" }}'
        AUTHENTIK_POSTGRESQL__PASSWORD: '{{ index . "password" }}'
        AUTHENTIK_POSTGRESQL__USE_PGBOUNCER: "false"
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-authentik-admin
