apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cert-manager-secret
  namespace: cert-manager
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        api-token: "{{ .api_token }}"
  dataFrom:
    - extract:
        key: *name
