---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-slow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readarr-cache
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-slow
