apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name gatus-secret
  namespace: observability
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SECRET_INTERNET_PING_URL: "{{ .SECRET_INTERNET_PING_URL }}"
  dataFrom:
    - extract:
        key: gatus-secret
