---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-secret
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: db-encryption
    template:
      engineVersion: v2
      data:
        db-encryption-key: "{{ .db_encryption_key }}"
  dataFrom:
    - extract:
        key: homarr-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-postgres
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres
  target:
    name: homarr-postgres
    template:
      engineVersion: v2
      data:
        db-url: "postgresql://{{ index . \"user\" }}:{{ index . \"password\" }}@{{ index . \"pgbouncer-host\" }}:{{ index . \"pgbouncer-port\" }}/{{ index . \"dbname\" }}"
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-homarr-admin
