---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-db-secret
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: db-encryption
    template:
      engineVersion: v2
      data:
        db-encryption-key: "{{ .db_encryption_key }}"
  dataFrom:
    - extract:
        key: homarr-secret
