---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homarr
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    env:
      TZ: ${TIMEZONE}
      REDIS_IS_EXTERNAL: "true"
      REDIS_HOST: dragonfly.database.svc.cluster.local
      REDIS_PORT: "6379"
    database:
      type: postgresql
    envSecrets:
      dbCredentials:
        existingSecret: homarr-postgres
    persistence:
      homarrDatabase:
        enabled: false
    ingress:
      enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi