---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: homarr
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      tag: v1.68.0
    env:
      TZ: ${TIMEZONE}
      REDIS_IS_EXTERNAL: "true"
      REDIS_HOST: dragonfly.database.svc.cluster.local
      REDIS_PORT: "6379"
      AUTH_PROVIDERS: "oidc,credentials"
      AUTH_OIDC_ISSUER: "https://keycloak.ewatkins.dev/realms/master"
      AUTH_OIDC_CLIENT_NAME: "Keycloak"
      AUTH_OIDC_AUTO_LOGIN: "false"
      AUTH_OIDC_GROUPS_LOCAL_MANAGEMENT: "true"
    database:
      type: postgresql
    envSecrets:
      authOidcCredentials:
        existingSecret: auth-oidc-secret
      dbCredentials:
        existingSecret: homarr-postgres
    persistence:
      homarrDatabase:
        enabled: false
    ingress:
      enabled: false