apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name cloudflared-secret
    namespace: network
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          TUNNEL_ID: "{{ .TUNNEL_ID }}"
          credentials.json: "{{ .credentials_json | b64dec }}"
    dataFrom:
      - extract:
          key: *name
