apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pulse-secret
  namespace: observability
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .PULSE_DOCKERCONFIGJSON | b64dec }}"
  dataFrom:
    - extract:
        key: pulse-secret
