apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name pulse-secret
  namespace: observability
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PULSE_BEARER_TOKEN: "{{ .PULSE_BEARER_TOKEN }}"
  dataFrom:
    - extract:
        key: pulse-secret
