---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudflare-tunnel
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudflare-dns
  path: ./kubernetes/apps/network/cloudflare-tunnel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: talos-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
