apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: &name unifi-dns-secret
    namespace: network
spec:
    refreshInterval: 15m
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-secrets-manager
    target:
      name: *name
      template:
        engineVersion: v2
        data:
          UNIFI_API_KEY: "{{ .api_token }}"
    dataFrom:
      - extract:
          key: *name
