apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name forgejo-admin-secret
  namespace: development
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        email: "{{ .email }}"
  dataFrom:
    - extract:
        key: *name
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name forgejo-security
  namespace: development
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        secret-key: "{{ .secret_key }}"
        internal-token: "{{ .internal_token }}"
  dataFrom:
    - extract:
        key: *name
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name forgejo-bucket
  namespace: development
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        MINIO_ACCESS_KEY_ID: "{{ .MINIO_ACCESS_KEY_ID }}"
        MINIO_SECRET_ACCESS_KEY: "{{ .MINIO_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: *name
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name forgejo-db
  namespace: development
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        POSTGRES_DBNAME: '{{ index . "dbname" }}'
        POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASS: '{{ index . "password" }}'
        POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-pguser-forgejo-admin
