---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
spec:
  users:
    - username: admin@ewatkins.dev
      role: Administrator
      passwordRef:
        name: pgadmin-secret
        key: PGADMIN_PASSWORD
  dataVolumeClaimSpec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
  serverGroups:
    - name: supply
      postgresClusterSelector: {}
  serviceName: pgadmin
