---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: garage-webui-oidc
  namespace: storage
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: garage-webui
  oidc:
    provider:
      issuer: https://keycloak.ewatkins.dev/realms/master
    clientID: garage-webui
    clientSecret:
      name: garage-secret
      namespace: storage
    redirectURL: "https://garage.ewatkins.dev/oauth2/callback"
    scopes: ["openid", "profile", "email"]
