---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: scanopy
  namespace: network
spec:
  endpoints:
    - ip:
        address: 10.35.50.4
        port: 60072
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: scanopy
  namespace: network
  annotations:
    external-dns.alpha.kubernetes.io/target: "internal.ewatkins.dev"
spec:
  parentRefs:
    - name: internal
      namespace: network
      sectionName: https
  hostnames: ["scanopy.ewatkins.dev"]
  rules:
    - backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: scanopy
