---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: observability
spec:
  chart:
    spec:
      chart: *app
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  interval: 15m
  dependsOn:
    - name: vpa
      namespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/containers/resources/limits
        target:
          kind: Pod
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.13.4
      pullPolicy: IfNotPresent

    controller:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 105Mi
        limits:
          memory: 132Mi

    dashboard:
      enabled: true
      replicaCount: 1
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        hosts:
          - host: &host "goldilocks.ewatkins.dev"
            paths:
              - path: /
                type: Prefix
      resources:
        requests:
          cpu: 15m
          memory: 105M
        limits:
          memory: 105M

    annotations:
      reloader.stakater.com/search: "true"
