---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: channel-identifiarr-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-slow
