---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"

  SUPERIOR: "192.168.40.11"
  HURON: "192.168.40.12"
  MICHIGAN: "192.168.40.13"
  ERIE: "192.168.40.14"
  ONTARIO: "192.168.40.15"
  TAHOE: "192.168.40.16"

  INTERNAL: "192.168.40.40"
  EXTERNAL: "192.168.40.30"

  NODE_CIDR_START: "192.168.40.100"
  NODE_CIDR_END: "192.168.40.245"

  JELLYFIN: "192.168.40.100"

  CRUNCHY_POSTGRES: "192.168.40.110"
  CRUNCHY_POSTGRES_PGBOUNCER: "192.168.40.150"

  # MARIADB
  MAXSCALE: "192.168.40.120"
  MAXSCALE_GUI: "192.168.40.121"
  MARIADB: "192.168.40.122"

  # VECTOR
  VECTOR: "192.168.40.130"

  # PULSE
  PULSE: "192.168.40.135"

  # GARAGE
  GARAGE: "192.168.40.140"

  # CODE-SERVER (http + ssh services share the IP via lb-ipam-sharing-key)
  CODE_SERVER: "192.168.40.145"
