---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"

  SUPERIOR: "10.40.1.1"
  HURON: "10.40.1.2"
  MICHIGAN: "10.40.1.3"
  ERIE: "10.40.1.4"
  ONTARIO: "10.40.1.5"

  INTERNAL: "10.40.0.10"
  EXTERNAL: "10.40.0.30"

  NODE_CIDR_START: "192.168.40.100"
  NODE_CIDR_END: "192.168.40.245"

  JELLYFIN: "192.168.40.100"

  CRUNCHY_POSTGRES: "192.168.40.110"

  # MARIADB
  MAXSCALE: "192.168.40.120"
  MAXSCALE_GUI: "192.168.40.121"
  MARIADB: "192.168.40.122"

  # VECTOR
  VECTOR: "192.168.40.130"

  # PULSE
  PULSE: "192.168.40.135"

  # GARAGE
  GARAGE: "192.168.40.140"

  # CODE-SERVER (http + ssh services share the IP via lb-ipam-sharing-key)
  CODE_SERVER: "192.168.40.145"
