---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name trek-secret
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        ENCRYPTION_KEY: "{{ .encryption_key }}"
  dataFrom:
    - extract:
        key: *name
