---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: enhanced-channel-manager-config
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-slow
