endpoints:
  - name: "${APP}"
    group: guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: false
      hide-url: false
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.ewatkins.dev"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
