endpoints:
  - name: "${APP}"
    group: Guarded
    url: 1.1.1.1
    interval: 1m
    ui:
      hide-hostname: false
      hide-url: false
    dns:
      query-name: "${GATUS_SUBDOMAIN:=${APP}}.ewatkins.dev"
      query-type: A
    conditions:
      - "len([BODY]) == 0"
    alerts:
      - type: pushover
        description: public DNS record found, endpoint is exposed
        minimum-reminder-interval: 4h
        provider-override:
          priority: 1
