#!/usr/bin/env bash
# Regenerate Grafana alert-rule provisioning from the cluster's PrometheusRules.
#
#   scripts/grafana-alert-rules.sh [--shadow]
#
# --shadow labels every rule (except Watchdog) grafana_shadow=true, which the
# Grafana policy tree mutes; use it while Alertmanager is still paging.
# Output replaces kubernetes/apps/observability/grafana/app/alerting/rules/.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="${ROOT_DIR}/kubernetes/apps/observability/grafana/app/alerting/rules"

for bin in kubectl python3 jq yq; do
  command -v "${bin}" >/dev/null || { echo "missing ${bin}" >&2; exit 1; }
done

tmp="$(mktemp -d)"
trap 'rm -rf "${tmp}"' EXIT

kubectl get prometheusrules --all-namespaces --output json \
  | python3 "${ROOT_DIR}/scripts/grafana-alert-rules.py" "$@" > "${tmp}/rules.jsonl"

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"
while IFS= read -r line; do
  file="$(jq -r '.file' <<<"${line}")"
  source="$(jq -r '.source' <<<"${line}")"
  {
    echo "---"
    echo "# Generated by scripts/grafana-alert-rules.sh from PrometheusRule ${source}."
    echo "# Do not edit by hand; change the source rule or the script and regenerate."
    jq '.doc' <<<"${line}" | yq --prettyPrint '.'
  } > "${OUT_DIR}/${file}"
done < "${tmp}/rules.jsonl"

# Kustomize can't glob, so the generated directory carries its own
# ConfigMap generator. Grafana reads alerting provisioning from one flat
# directory; the HelmRelease projects this ConfigMap next to grafana-alerting.
{
  echo "---"
  echo "# Generated by scripts/grafana-alert-rules.sh."
  echo "# yaml-language-server: \$schema=https://json.schemastore.org/kustomization"
  echo "apiVersion: kustomize.config.k8s.io/v1beta1"
  echo "kind: Kustomization"
  echo "configMapGenerator:"
  echo "  - name: grafana-alerting-rules"
  echo "    files:"
  find "${OUT_DIR}" -name '*.yaml' ! -name kustomization.yaml -printf '%f\n' | sort | sed 's/^/      - .\//'
  echo "generatorOptions:"
  echo "  disableNameSuffixHash: true"
  echo "  annotations:"
  echo "    kustomize.toolkit.fluxcd.io/substitute: disabled"
  echo "    reloader.stakater.com/match: \"true\""
} > "${OUT_DIR}/kustomization.yaml"

echo "wrote $(find "${OUT_DIR}" -name '*.yaml' ! -name kustomization.yaml | wc -l) rule files," \
  "$(find "${OUT_DIR}" -name '*.yaml' ! -name kustomization.yaml -exec cat {} + | yq -N '.groups[].rules[].uid' | wc -l) rules to ${OUT_DIR#"${ROOT_DIR}"/}"
