endpoints:
  - name: "${APP}"
    group: internal
    url: "https://${GATUS_SUBDOMAIN:-${APP}}.${GATUS_DOMAIN:-ewatkins.dev}"
    interval: 1m
    ui:
      hide-hostname: false
      hide-url: false
    conditions:
      - "[STATUS] == ${GATUS_STATUS:-200}"
