---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redisinsight
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/containers/resources/limits
        target:
          kind: Pod
  values:
    defaultPodOptions:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

    controllers:
      redisinsight:
        annotations:
          reloader.stakater.com/search: "true"
        strategy: Recreate
        containers:
          app:
            image:
              repository: redis/redisinsight
              tag: 2.70.0
            env:
              - name: RI_FILES_LOGGER
                value: "false"
              - name: RI_STDOUT_LOGGER
                value: "true"
            resources:
              requests:
                cpu: 15m
                memory: 204M
              limits:
                memory: 204M
            securityContext:
              allowPrivilegeEscalation: false
              # readOnlyRootFilesystem: true
              capabilities: { drop: [ALL] }
    service:
      app:
        # name should not be 'redisinsight'  since the service creates environment variables
        # that conflicts with redisinsight application's environment variables:
        # `REDISINSIGHT_HOST` and `REDISINSIGHT_PORT`
        nameOverride: redisinsight-svc
        controller: *app
        ports:
          http:
            port: 5540

    serviceAccount:
      create: true
    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.ewatkins.dev"
        hosts:
          - host: &host redis.ewatkins.dev
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
