apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name forgejo-runner-secret
  namespace: development
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        FORGEJO_INSTANCE_URL: "{{ .FORGEJO_INSTANCE_URL }}"
        RUNNER_NAME: "{{ .RUNNER_NAME }}"
        RUNNER_TOKEN: "{{ .RUNNER_TOKEN }}"
  dataFrom:
    - extract:
        key: *name
