---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app jellyfin
  namespace: flux-system
spec:
  targetNamespace: media
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/media
  dependsOn:
    - name: external-secrets-stores
  wait: false
  path: ./kubernetes/apps/media/jellyfin/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: talos-cluster
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      GATUS_PATH: /web/index.html

