---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: default
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: homepage-secret
  dataFrom:
    - extract:
        key: homepage-secret
