---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBECONFORM_SCRIPT: "{{.SCRIPTS_DIR}}/kubeconform.sh"

tasks:
  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
      - for: { var: resource }
        cmd: kubecolor get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      resource:
        [
          "nodes -o wide",
          "gitrepositories",
          "kustomizations",
          "helmrepositories",
          "helmreleases",
          "certificates -o wide",
          "certificaterequests -o wide",
          "ingresses",
          "services",
          "pods -o wide",
        ]

  validate:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
    preconditions:
      - {
          msg: "Missing kubeconform script",
          sh: "test -f {{.KUBECONFORM_SCRIPT}}",
        }

  browse-pvc:
    desc: Browse PersistentVolumeClaims
    summary: |
      Args:
        ns: Namespace to browse PersistentVolumeClaims in (default: default)
        claim: PersistentVolumeClaim to browse (required)
    interactive: true
    cmd: kubectl browse-pvc --namespace {{.ns}} {{.claim}}
    vars:
      ns: '{{.ns | default "default"}}'
    requires:
      vars: ["claim"]

  drain:
    desc: Drain a node
    summary: |
      Args:
        node: Node to drain (required)
    vars:
      NODE: "{{.CLI_ARGS | default .node}}"
    cmds:
      - kubecolor drain {{.NODE}} --ignore-daemonsets --delete-emptydir-data

  clear-failed:
    desc: Deletes pods with a failed status
    cmds:
      - for: ["Evicted", "Failed", "Succeeded"]
        cmd: kubecolor delete pods --field-selector status.phase={{.ITEM}} -A --ignore-not-found=true

  # https://docs.github.com/en/enterprise-cloud@latest/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/deploying-runner-scale-sets-with-actions-runner-controller#upgrading-arc
  upgrade-arc:
    desc: Upgrade the ARC
    cmds:
      - helm -n actions-runner-system uninstall talos-runner
      - helm -n actions-runner-system uninstall actions-runner-controller
      - sleep 5
      - flux -n actions-runner-system reconcile hr actions-runner-controller
      - flux -n actions-runner-system reconcile hr talos-runner
    preconditions:
      - which flux helm
