endpoints:
  - name: "${APP}"
    group: media
    url: "https://${GATUS_SUBDOMAIN:-${APP}}.${GATUS_DOMAIN:-ewatkins.dev}${GATUS_PATH:-/}"
    interval: 1m
    conditions:
      - "[STATUS] == ${GATUS_STATUS:-200}"
