---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: 0.19.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    installCRDs: true

    bitwarden-sdk-server:
      enabled: true
      podAnnotations:
        secret.reloader.stakater.com/reload: "bitwarden-css-certs,bitwarden-secrets-manager,bitwarden-secrets-manager-secrets,bitwarden-tls-certs,bitwarden-access-token"

    # grafana:
    #   enabled: true

    serviceMonitor:
      enabled: true
      interval: 1m

    certController:
      serviceMonitor:
        enabled: true
        interval: 1m

    reportsController:
      serviceMonitor:
        enabled: true
        interval: 1m

    # webhook:
    #   image:
    #     repository: ghcr.io/external-secrets/external-secrets
    #   serviceMonitor:
    #     enabled: true
    #     interval: 1m
