---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
data:
  TZ: ${TIMEZONE}
  REDIS_HOSTNAME: dragonfly.database.svc.cluster.local
  REDIS_PORT: "6379"
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.media.svc.cluster.local:3003
