---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name immich-db-secret
  namespace: media
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres
  target:
    name: *name
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      data:
        DB_URL: 'postgresql://{{ index . "user" }}:{{ index . "password" }}@crunchy-postgres-vector-ha.database.svc:5432/{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: crunchy-postgres-vector-pguser-immich
