---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      immich-server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.144.1
            envFrom:
              - secretRef:
                  name: immich-db-secret
              - configMapRef:
                  name: immich-config
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: &port 2283
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 512Mi
              limits:
                memory: 4Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        controller: immich-server
        ports:
          http:
            port: *port
    route:
      main:
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.ewatkins.dev"
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        hostnames:
          - "photos.ewatkins.dev"
        rules:
          - matches:
              - path:
                  type: PathPrefix
                  value: /
            filters:
              - type: ResponseHeaderModifier
                responseHeaderModifier:
                  add:
                    - name: Strict-Transport-Security
                      value: "max-age=31449600; includeSubDomains"
            backendRefs:
              - name: immich-server
                port: *port
    persistence:
      library:
        existingClaim: immich-library
        globalMounts:
          - path: /usr/src/app/upload
