---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Release"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # 1st of every month at midnight

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Create Release
        uses: mirceanton/action-calver-release@e34e40c96ed4998c9a0adb0c8d3d821b49d789a3 # 2025.11.4
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          dry-run: false
